// Main
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';
export const SET_CONNECTION_INFO = 'SET_CONNECTION_INFO';

export const RESET_STATE = 'RESET_STATE';
export const SET_LAST_VERSION = 'SET_LAST_VERSION';

// Preview
export const PREVIEW_LOADING = 'PREVIEW_LOADING';
export const PREVIEW = 'PREVIEW';
