// Main
export const AUTO_COMPLETE = 'AUTO_COMPLETE';
export const AUTO_COMPLETE_SET_STRING = 'AUTO_COMPLETE_SET_STRING';
export const AUTO_COMPLETE_CLEAR = 'AUTO_COMPLETE_CLEAR';
export const AUTO_COMPLETE_BLOCK_IDENTIFIER = 'AUTO_COMPLETE_BLOCK_IDENTIFIER';
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';
export const SET_UPDATE_STATUS = 'SET_UPDATE_STATUS';
export const CACHE_SAVE = 'CACHE_SAVE';
export const CACHE_CLEAR = 'CACHE_CLEAR';
export const RESET_STATE = 'RESET_STATE';
export const SET_LAST_VERSION = 'SET_LAST_VERSION';

// filters
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const UPDATE_NOTIFICATION_COUNTER = 'UPDATE_NOTIFICATION_COUNTER';
export const FILTER_UPDATE = 'FILTER_UPDATE';
export const FILTER_CLEAR = 'FILTER_CLEAR';

// Notification
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';

// Notes
export const NOTE_CACHE = 'NOTE_CACHE';
export const NOTE_SAVE = 'NOTE_SAVE';
export const NOTE_SAVE_START = 'NOTE_SAVE_START';
export const NOTE_SAVE_SUCCESS = 'NOTE_SAVE_SUCCESS';
export const NOTE_SAVE_ERROR = 'NOTE_SAVE_ERROR';

// Search
export const SEARCH = 'SEARCH';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

// Preview
export const PREVIEW_LOADING = 'PREVIEW_LOADING';
export const PREVIEW = 'PREVIEW';
